version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notificationservice
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  mongodb_data: 