apiVersion: apps/v1
kind: Deployment
metadata:
  name: userms
  labels:
    app: userms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userms
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
        - name: userms
          image: userms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: userms
spec:
  selector:
    app: userms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082 