apiVersion: apps/v1
kind: Deployment
metadata:
  name: userms
  labels:
    app: userms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userms
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
        - name: userms
          image: userms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/user_database"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: userms
spec:
  selector:
    app: userms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 