services:
  #  APPS
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017/questiondb?authSource=admin
      spring.data.mongodb.database: questiondb

  
  # MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: questiondb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/questiondb?authSource=admin
      ME_CONFIG_BASICAUTH: false

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ protocol (AMQP)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest