version: "3.8"
services:
  notification-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
