apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==      # root (base64 encoded)
  password: ZXhhbXBsZQ==  # example (base64 encoded)
  uri: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiLWhlYWRsZXNzOjI3MDE3L25vdGlmaWNhdGlvbnM/YXV0aFNvdXJjZT1hZG1pbg==  # mongodb://root:example@mongodb-headless:27017/notifications?authSource=admin
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  erlang-cookie: UkFCQklUTVFfQ09PS0lFX1NFQ1JFVA==  # RABBITMQ_COOKIE_SECRET 
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: dXNlcl91c2VybmFtZQ==  # user_username (base64 encoded)
  password: dXNlcl9wYXNzd29yZA==  # user_password (base64 encoded) 