
services:
  postgres:
    image: postgres
    container_name: postgres-user-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_database
      POSTGRES_USER: user_username
      POSTGRES_PASSWORD: user_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  userms:
    build:
      dockerfile: Dockerfile
    container_name: user-ms
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_database
      SPRING_DATASOURCE_USERNAME: user_username
      SPRING_DATASOURCE_PASSWORD: user_password

volumes:
  postgres-data: