version: '3.8'

services:
    
  course-service:
    build: .
    ports:
      - "8081:8081"
      
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/course_service
      - USER_SERVICE_URL=http://userms:8080
      - SERVER_PORT=8081  
    networks:
        - shared-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - shared-network

volumes:
  mongo-data:

networks:
  shared-network: 
    driver: bridge