spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notifications
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: kubernetes
  data:
    mongodb:
      uri: mongodb://root:example@mongodb-headless:27017/notifications?authSource=admin
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
