apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionservice
  labels:
    app: questionservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: questionservice
  template:
    metadata:
      labels:
        app: questionservice
    spec:
      containers:
      - name: questionservice
        image: questionservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: guest
        - name: SPRING_RABBITMQ_PASSWORD
          value: guest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10 